### ISSUE TITLE
missing duration parameter?

### ISSUE THREAD

**Issue by kheftel** [Gamua/Starling-Extension-Particle-System#28]
In Particle Designer, you can assign a duration.  You might use 0.1 for something like an explosion or firework, and -1 (unlimited) for something like smoke or fire that should run constantly.

This extension doesn't seem to parse/remember/respect that duration.

I would like to be able to write something like this:
`particle.start(particle.duration);`

As it is, it appears I have to parse the XML myself to find the desired duration that I set in Particle Designer, or hard-code it into my code.

**Comment by PrimaryFeather** [comment]
That should do it! There's now a new property called `defaultDuration`.
I hope that helps! :smile:

**Comment by kheftel** [comment]
That's awesome! As I mentioned in #29, I'm not able to update to HEAD at this time, but I did parse the XML in my code, and this should benefit others :)
