### ISSUE TITLE
Bug in particle editor

### ISSUE THREAD

**Issue by kheftel** [Gamua/Starling-Extension-Particle-System#29]
Started using the "real" Particle Desginer by 71squared recently, instead of the online one at http://onebyonedesign.com/flash/particleeditor/.

It looks like there's a bug in the online particle editor where what should be `finishParticleSizeVariance` is exported as `FinishParticleSizeVariance `.  This bug doesn't exist in Particle Designer by 71squared.

Looks like PDParticleSystem expects the bug to be there, i.e. it looks for the incorrect `FinishParticleSizeVariance` in the config XML.  The NaN's that resulted cost me almost a full day's work today trying to figure out why particles from the online tool displayed fine, but particles from Particle Designer didn't display at all. I assume this was done in order to not break particles exported by the online tool.

It would seem we need to have some way of accounting for the bug, or at least return 0 for any unknown variables in `parseConfig` instead of NaNs.

If I can figure out how to do a pull request, I will do so!

**Comment by PrimaryFeather** [comment]
> The NaN's that resulted cost me almost a full day's work today [...]

Damn, that's extremely annoying. Sorry for that! :pensive:

That reason that the particle designer from OneByOneDesign has that typo is that the old version of the 71squared editor had the same one. :wink:

However, I actually anticipated that there could be problems with this and added a workaround that *should* guard for that problem: [PDParticleSystem.as#L262](https://github.com/Gamua/Starling-Extension-Particle-System/blob/master/src/starling/extensions/PDParticleSystem.as#L262). Could you check what's happening here that it doesn't enter this `if`-clause?

**Comment by kheftel** [comment]
It doesn't enter the if clause, because it doesn't exist!! I forgot to mention I'm using Starling 1.x in this project and I have NO idea how old my copy of `PDParticleSystem.as` is!  My bad for complaining about an already-fixed problem, I thought I checked the head revision before posting but I guess not...

Anyway, I patched it in my local version, similarly to how you did in the head revision. I want to update to Starling 2.x at some point, however, I'm using a Feathers 1.x theme and AFAIK Starling 2 is not compatible with Feathers 1.x, correct? I'd have to rewrite our custom theme for Feathers 2 or 3 and I'd need approval from the client to justify the extra expense ;).

**Comment by PrimaryFeather** [comment]
No worries, I'm glad you could solve it like that! :-)

BTW, I'm also maintaining a branch that's compatible with Starling 1.8: 
https://github.com/Gamua/Starling-Extension-Particle-System/tree/v1.8.x

That one should contain the uppercase fix, as well.

**Comment by kheftel** [comment]
oh cool, that's good to know. I think this project is still on starling 1.5 but if I'm able to upgrade it I'll check it out.
