### ISSUE TITLE
"BlendMode.isRegistered" and "BlendMode.getAll" do not exist in Starling Latest

### ISSUE THREAD

**Issue by 2jfw** [Gamua/Starling-Extension-Particle-System#34]
I am trying to get the Starling-Particle-Editor to compile with the latest commit of "Starling-Extension-Particle-System" and get the following compiler errors:

`[Starling-Particle-Editor - Main]: Call to a possibly undefined method isRegistered through a reference with static type BlendMode.`
`[Starling-Particle-Editor - Main]: Call to a possibly undefined method getAll through a reference with static type BlendMode.`

I made sure that BlendMode is properly pointing to "starling.display.BlendMode".
I am using latest Starling.swc.

The latest documentation of BlendMode does not list these two methods (https://doc.starling-framework.org/current/starling/display/BlendMode.html).

Am I missing something?

**Comment by Adolio** [comment]
Hi,

That's normal, this is coming from a recent change in this extension. The Starling `master` branch contains those methods but the current official release (.swc) doesn't yet.

Your have two options:

1) Use the `master` version of Starling by linking it in your classpath.

2) Use a slightly earlier version of this library (this commit should be fine: b80ef8a).

Best,
Aurélien

**Comment by 2jfw** [comment]
Thanks for your help! I will then stick to the latest master.

(I did actually google for anything like "Starling + BlendMode + isRegistered" before asking but there are no results as of yet)
